### ISSUE TITLE
should the new email address be verified when 'emailChange'?

### ISSUE THREAD

**Issue by beeplin** [eddyystop/feathers-service-verify-reset#19] opened 2016-11-10 10:38 UTC
Currently we only verify email address when users sign up. But when they call `emailChange`, the new email address isn't verified. Would this be a problem?

**Comment by eddyystop** [comment] 2016-11-10 12:28
Thanks. I'll look into this when I'm free.

**Comment by eddyystop** [comment] 2016-11-11 14:44
There are 2 purposes to verifying a person's email on signup
- Force bots and hackers to create (or already have) a separate email addr for each signup.
- Verify the email addr is correct (since there is no way to parse an email addr 100%) and that it exists.

Only the second concern exists on an email change. A wrong email addr does not prevent the user from signing on, nor from correcting the email addr.

So the question is whether the benefit is worth the added complexity? The complexity being (1) maybe even keeping both email addrs around until reverification (2) its awkward to ask to person to do something if they do **not** receive an email.

**Comment by beeplin** [comment] 2016-11-11 15:03
my concern is that sometimes it is important to make sure the user is the real owner of the email address. for example, i signed up with my own email and then changed it to your email. then when you want to sign up the same website, you found your email is occupied. that would be frustrating.

**Comment by eddyystop** [comment] 2016-11-11 16:00
I assume we keep both the old and new email addrs in the user item. The old one remains the current one until the new one is verified.

During verification, either `isVerified === false && newEmail === undefined` or `isVerified === true && newEmail !== undefined` and that determines what is to be done.

**Comment by beeplin** [comment] 2016-11-12 14:39
yeah this will work. Cool!

**Comment by eddyystop** [comment] 2016-11-17 19:45
Now a duplicate of https://github.com/eddyystop/feathers-service-verify-reset/issues/18

**Closed as completed by eddyystop** 2016-11-17 19:45 UTC
Labels: discuss
